### ISSUE TITLE
X-Accel extension

### ISSUE THREAD

**Issue by kamzata** [ononoki1/nginx-quictls#24]
Hi,

any chances for you to include [X-Accel extension](https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/) in the build?

Thanks

**Comment by ononoki1** [comment]
It should just work out of the box as X-Accel works as a header instead of standalone module.

> This feature differs a bit from standard NGINX modules as it does not rely on directives but rather handles headers from upstream in a special way.

**Comment by kamzata** [comment]
I'm placing Odoo behind it. [Odoo docs say](https://www.odoo.com/documentation/17.0/administration/install/deploy.html#serving-attachments):

> For Odoo to delegate serving files to the static web server, the [X-Sendfile](https://tn123.org/mod_xsendfile/) (apache) or [X-Accel](https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/) (nginx) extensions must be enabled and configured on the static web server.
