### ISSUE TITLE
Downloads sometimes are interrupted at different size

### ISSUE THREAD

**Issue by kamzata** [ononoki1/nginx-quictls#25]
A lot users of one of my website behind Nginx, starting from around 2/3 months ago, tell me that file downloads (usually file from 50MB to 2GB) are interrupted. They told me the downloads stop but every user refers stop at different size.

I noticed in the last period of time the users that are complaining this are increasingly. Personally, I tried to replicate the problem but without success. I tried to use 3/4 different internet connections and different browsers but for me has always worked.

Are you informed of any Nginx breaking change about this?

**Comment by ononoki1** [comment]
You may need to set `proxy_max_temp_file_size 0;`. See this ticket: https://trac.nginx.org/nginx/ticket/1472

**Comment by kamzata** [comment]
> You may need to set `proxy_max_temp_file_size 0;`. See this ticket: https://trac.nginx.org/nginx/ticket/1472

Tried but that doesn't seem to help, thanks.
